import type { EmployeeRecord, OrgSettings } from './types';

const now = new Date();

function minutesAgo(minutes: number) {
  const d = new Date(now);
  d.setMinutes(d.getMinutes() - minutes);
  return d.toISOString();
}

export const workforceSettings: OrgSettings = {
  schedulingEnabled: true,
  overtimeEnabled: true,
  kioskPhotoEnabled: true,
  geofenceEnabled: true,
};

export const workforceEmployees: EmployeeRecord[] = [
  {
    id: 'e-001',
    name: 'Ramona Flowers',
    role: 'Front Desk Lead',
    avatarUrl: 'https://i.pravatar.cc/80?img=5',
    status: 'CLOCKED_IN',
    currentSession: {
      clockInTime: minutesAgo(310),
      method: 'KIOSK',
      location: { lat: 40.299, lng: -111.694, label: 'Draper HQ' },
      photoUrl: 'https://i.pravatar.cc/120?img=5',
      faceMatchScore: 0.92,
      locationConsistencyScore: 0.9,
      deviceFamiliarityScore: 0.88,
    },
    baselines: {
      startWindow: { start: '07:45', end: '08:20' },
      shiftLengthMinutes: 510,
      breakLengthMinutes: 30,
      usualLocationLabel: 'Draper HQ',
    },
    overtime: { thresholdHours: 40, workedThisWeekHours: 38.7 },
    timeIntegrity: { unassignedHours: 0.3, editsCount: 1, submittedHours: 39 },
    history: {
      recentAnomalies: [
        { type: 'OVERTIME_RISK', happenedAt: minutesAgo(1800) },
        { type: 'OVERTIME_RISK', happenedAt: minutesAgo(4500) },
      ],
    },
  },
  {
    id: 'e-002',
    name: 'Ben Proctor',
    role: 'Cashier',
    avatarUrl: 'https://i.pravatar.cc/80?img=12',
    status: 'ON_BREAK',
    currentSession: {
      clockInTime: minutesAgo(205),
      breakStartTime: minutesAgo(47),
      method: 'MOBILE',
      location: { lat: 40.221, lng: -111.66, label: 'Remote - South Lot' },
      faceMatchScore: 0.65,
      locationConsistencyScore: 0.55,
      deviceFamiliarityScore: 0.82,
    },
    baselines: {
      startWindow: { start: '08:00', end: '08:30' },
      shiftLengthMinutes: 480,
      breakLengthMinutes: 25,
      usualLocationLabel: 'Draper HQ',
    },
    overtime: { thresholdHours: 40, workedThisWeekHours: 30.5 },
    timeIntegrity: { unassignedHours: 1.6, editsCount: 3, submittedHours: 32.1 },
    history: {
      recentAnomalies: [
        { type: 'BREAK_RISK', happenedAt: minutesAgo(300) },
        { type: 'BREAK_RISK', happenedAt: minutesAgo(4200) },
      ],
    },
  },
  {
    id: 'e-003',
    name: 'Albert Flores',
    role: 'Front Desk',
    avatarUrl: 'https://i.pravatar.cc/80?img=16',
    status: 'CLOCKED_IN',
    currentSession: {
      clockInTime: minutesAgo(530),
      method: 'MOBILE',
      location: { lat: 40.301, lng: -111.69, label: 'Draper HQ' },
      faceMatchScore: 0.8,
      locationConsistencyScore: 0.84,
      deviceFamiliarityScore: 0.74,
    },
    baselines: {
      startWindow: { start: '08:00', end: '08:15' },
      shiftLengthMinutes: 480,
      breakLengthMinutes: 30,
      usualLocationLabel: 'Draper HQ',
    },
    overtime: { thresholdHours: 40, workedThisWeekHours: 35.9 },
    timeIntegrity: { unassignedHours: 0.1, editsCount: 0, submittedHours: 36 },
    history: {
      recentAnomalies: [{ type: 'BEHAVIOR_DEVIATION', happenedAt: minutesAgo(1400) }],
    },
  },
  {
    id: 'e-004',
    name: 'Janet Caldwell',
    role: 'Support Specialist',
    avatarUrl: 'https://i.pravatar.cc/80?img=28',
    status: 'CLOCKED_OUT',
    currentSession: {
      method: 'MOBILE',
      location: { lat: 40.299, lng: -111.694, label: 'Draper HQ' },
      faceMatchScore: 0.89,
      locationConsistencyScore: 0.9,
      deviceFamiliarityScore: 0.9,
    },
    baselines: {
      startWindow: { start: '08:30', end: '09:00' },
      shiftLengthMinutes: 450,
      breakLengthMinutes: 30,
      usualLocationLabel: 'Draper HQ',
    },
    overtime: { thresholdHours: 40, workedThisWeekHours: 27.4 },
    timeIntegrity: { unassignedHours: 0.0, editsCount: 1, submittedHours: 27.4 },
    history: { recentAnomalies: [] },
    lastClockOutAt: minutesAgo(22),
  },
  {
    id: 'e-005',
    name: 'Devon Lane',
    role: 'Cashier',
    avatarUrl: 'https://i.pravatar.cc/80?img=33',
    status: 'CLOCKED_IN',
    currentSession: {
      clockInTime: minutesAgo(120),
      method: 'KIOSK',
      location: { lat: 40.18, lng: -111.71, label: 'Unknown Lot' },
      photoUrl: 'https://i.pravatar.cc/120?img=33',
      faceMatchScore: 0.44,
      locationConsistencyScore: 0.4,
      deviceFamiliarityScore: 0.39,
    },
    baselines: {
      startWindow: { start: '07:30', end: '08:00' },
      shiftLengthMinutes: 450,
      breakLengthMinutes: 25,
      usualLocationLabel: 'Draper HQ',
    },
    overtime: { thresholdHours: 40, workedThisWeekHours: 18.3 },
    timeIntegrity: { unassignedHours: 2.1, editsCount: 5, submittedHours: 20.4 },
    history: {
      recentAnomalies: [
        { type: 'PRESENCE_CONFIDENCE', happenedAt: minutesAgo(1200) },
        { type: 'TIME_INTEGRITY', happenedAt: minutesAgo(3600) },
      ],
    },
  },
  {
    id: 'e-006',
    name: 'Ronald Richards',
    role: 'Scheduler',
    avatarUrl: 'https://i.pravatar.cc/80?img=45',
    status: 'CLOCKED_IN',
    currentSession: {
      clockInTime: minutesAgo(90),
      method: 'MOBILE',
      location: { lat: 40.299, lng: -111.694, label: 'Draper HQ' },
      faceMatchScore: 0.94,
      locationConsistencyScore: 0.95,
      deviceFamiliarityScore: 0.96,
    },
    baselines: {
      startWindow: { start: '08:00', end: '08:30' },
      shiftLengthMinutes: 480,
      breakLengthMinutes: 30,
      usualLocationLabel: 'Draper HQ',
    },
    overtime: { thresholdHours: 40, workedThisWeekHours: 22.1 },
    timeIntegrity: { unassignedHours: 0.0, editsCount: 0, submittedHours: 22.1 },
    history: { recentAnomalies: [] },
  },
  {
    id: 'e-007',
    name: 'Ava Patel',
    role: 'Inventory Associate',
    avatarUrl: 'https://i.pravatar.cc/80?img=50',
    scheduleTag: 'UNSCHEDULED',
    status: 'CLOCKED_OUT',
    currentSession: {
      method: 'MOBILE',
      location: { lat: 40.299, lng: -111.694, label: 'Draper HQ' },
      faceMatchScore: 0.88,
      locationConsistencyScore: 0.9,
      deviceFamiliarityScore: 0.91,
    },
    baselines: {
      startWindow: { start: '09:00', end: '09:30' },
      shiftLengthMinutes: 480,
      breakLengthMinutes: 30,
      usualLocationLabel: 'Draper HQ',
    },
    overtime: { thresholdHours: 40, workedThisWeekHours: 14.2 },
    timeIntegrity: { unassignedHours: 0.0, editsCount: 0, submittedHours: 14.2 },
    history: { recentAnomalies: [] },
  },
  {
    id: 'e-008',
    name: 'Liam Carter',
    role: 'Support Specialist',
    avatarUrl: 'https://i.pravatar.cc/80?img=58',
    scheduleTag: 'UNSCHEDULED',
    status: 'CLOCKED_OUT',
    currentSession: {
      method: 'MOBILE',
      location: { lat: 40.299, lng: -111.694, label: 'Draper HQ' },
      faceMatchScore: 0.9,
      locationConsistencyScore: 0.92,
      deviceFamiliarityScore: 0.93,
    },
    baselines: {
      startWindow: { start: '08:00', end: '08:30' },
      shiftLengthMinutes: 480,
      breakLengthMinutes: 30,
      usualLocationLabel: 'Draper HQ',
    },
    overtime: { thresholdHours: 40, workedThisWeekHours: 19.8 },
    timeIntegrity: { unassignedHours: 0.0, editsCount: 0, submittedHours: 19.8 },
    history: { recentAnomalies: [] },
  },
  {
    id: 'e-009',
    name: 'Mia Thompson',
    role: 'Front Desk',
    avatarUrl: 'https://i.pravatar.cc/80?img=62',
    scheduleTag: 'PTO',
    status: 'CLOCKED_OUT',
    currentSession: {
      method: 'MOBILE',
      location: { lat: 40.299, lng: -111.694, label: 'Draper HQ' },
      faceMatchScore: 0.9,
      locationConsistencyScore: 0.91,
      deviceFamiliarityScore: 0.89,
    },
    baselines: {
      startWindow: { start: '08:30', end: '09:00' },
      shiftLengthMinutes: 480,
      breakLengthMinutes: 30,
      usualLocationLabel: 'Draper HQ',
    },
    overtime: { thresholdHours: 40, workedThisWeekHours: 21.0 },
    timeIntegrity: { unassignedHours: 0.0, editsCount: 0, submittedHours: 21.0 },
    history: { recentAnomalies: [] },
  },
];
