import type { Alert, Employee, Insight } from '../types/managerLiveView';

const employees: Employee[] = [
  {
    id: 'e-101',
    name: 'Jake Patel',
    avatarUrl: null,
    role: 'Line Lead',
    department: 'Operations',
    location: 'Denver HQ',
    status: 'on_break',
    scheduledStart: '07:00',
    scheduledEnd: '15:00',
    todayMinutes: 370,
    weekMinutes: 2060,
    lastPunch: '2026-03-02T13:01:00Z',
    exceptions: [
      { type: 'break_over', minutesOver: 6 },
      { type: 'meal_due', minutesOver: 20 },
    ],
    punches: [
      { date: '2026-02-19', minutesLate: 9 },
      { date: '2026-02-21', minutesLate: 11 },
      { date: '2026-02-25', minutesLate: 7 },
      { date: '2026-02-28', minutesLate: 10 },
    ],
  },
  {
    id: 'e-102',
    name: 'Maria Chen',
    avatarUrl: null,
    role: 'Warehouse Associate',
    department: 'Operations',
    location: 'Denver HQ',
    status: 'clocked_in',
    scheduledStart: '08:00',
    scheduledEnd: '16:30',
    todayMinutes: 355,
    weekMinutes: 1980,
    lastPunch: '2026-03-02T08:12:00Z',
    exceptions: [{ type: 'missed_punch' }],
    punches: [
      { date: '2026-02-17', minutesLate: 12 },
      { date: '2026-02-24', minutesLate: 0 },
      { date: '2026-02-27', minutesLate: 5 },
    ],
  },
  {
    id: 'e-103',
    name: 'Alonzo Rivera',
    avatarUrl: null,
    role: 'Support Rep',
    department: 'Customer Support',
    location: 'Salt Lake City',
    status: 'clocked_in',
    scheduledStart: '09:00',
    scheduledEnd: '17:00',
    todayMinutes: 425,
    weekMinutes: 2320,
    lastPunch: '2026-03-02T09:04:00Z',
    exceptions: [{ type: 'ot_soon' }],
    punches: [
      { date: '2026-02-20', minutesLate: 4 },
      { date: '2026-02-26', minutesLate: 0 },
    ],
  },
  {
    id: 'e-104',
    name: 'Priya Gomez',
    avatarUrl: null,
    role: 'Store Manager',
    department: 'Retail',
    location: 'Boulder',
    status: 'absent',
    scheduledStart: '06:30',
    scheduledEnd: '14:30',
    todayMinutes: 0,
    weekMinutes: 1620,
    exceptions: [{ type: 'missed_punch' }],
    punches: [
      { date: '2026-02-22', minutesLate: 6 },
      { date: '2026-02-27', minutesLate: 8 },
    ],
  },
  {
    id: 'e-105',
    name: 'Ethan Brooks',
    avatarUrl: null,
    role: 'HR Generalist',
    department: 'People Ops',
    location: 'Remote',
    status: 'pto',
    scheduledStart: '08:00',
    scheduledEnd: '17:00',
    todayMinutes: 0,
    weekMinutes: 1200,
    punches: [{ date: '2026-02-18', minutesLate: 0 }],
  },
  {
    id: 'e-106',
    name: 'Nora Williams',
    avatarUrl: null,
    role: 'Analyst',
    department: 'Finance',
    location: 'Denver HQ',
    status: 'clocked_out',
    scheduledStart: '07:00',
    scheduledEnd: '15:00',
    todayMinutes: 420,
    weekMinutes: 2280,
    exceptions: [{ type: 'left_early', minutesOver: 8 }],
    punches: [
      { date: '2026-02-19', minutesLate: 0 },
      { date: '2026-02-23', minutesLate: 3 },
    ],
  },
  {
    id: 'e-107',
    name: 'Liam Thompson',
    avatarUrl: null,
    role: 'Forklift Operator',
    department: 'Operations',
    location: 'Denver HQ',
    status: 'clocked_in',
    scheduledStart: '06:00',
    scheduledEnd: '14:00',
    todayMinutes: 462,
    weekMinutes: 2385,
    lastPunch: '2026-03-02T06:03:00Z',
    exceptions: [{ type: 'ot_soon' }],
    punches: [
      { date: '2026-02-20', minutesLate: 2 },
      { date: '2026-02-24', minutesLate: 4 },
      { date: '2026-02-28', minutesLate: 1 },
    ],
  },
  {
    id: 'e-108',
    name: 'Sophia Miller',
    avatarUrl: null,
    role: 'Cashier',
    department: 'Retail',
    location: 'Boulder',
    status: 'on_break',
    scheduledStart: '10:00',
    scheduledEnd: '18:00',
    todayMinutes: 286,
    weekMinutes: 1720,
    lastPunch: '2026-03-02T13:10:00Z',
    exceptions: [{ type: 'break_over', minutesOver: 4 }],
    punches: [
      { date: '2026-02-18', minutesLate: 6 },
      { date: '2026-02-25', minutesLate: 5 },
    ],
  },
  {
    id: 'e-109',
    name: 'Noah Davis',
    avatarUrl: null,
    role: 'Support Specialist',
    department: 'Customer Support',
    location: 'Salt Lake City',
    status: 'clocked_out',
    scheduledStart: '08:00',
    scheduledEnd: '16:30',
    todayMinutes: 478,
    weekMinutes: 2450,
    lastPunch: '2026-03-02T15:52:00Z',
    exceptions: [{ type: 'left_early', minutesOver: 10 }],
    punches: [
      { date: '2026-02-19', minutesLate: 7 },
      { date: '2026-02-26', minutesLate: 9 },
    ],
  },
  {
    id: 'e-110',
    name: 'Ava Johnson',
    avatarUrl: null,
    role: 'Recruiter',
    department: 'People Ops',
    location: 'Remote',
    status: 'clocked_in',
    scheduledStart: '09:00',
    scheduledEnd: '17:00',
    todayMinutes: 331,
    weekMinutes: 1895,
    lastPunch: '2026-03-02T09:08:00Z',
    exceptions: [{ type: 'meal_due', minutesOver: 15 }],
    punches: [
      { date: '2026-02-20', minutesLate: 3 },
      { date: '2026-02-24', minutesLate: 0 },
      { date: '2026-02-27', minutesLate: 6 },
    ],
  },
  {
    id: 'e-111',
    name: 'Mason Lee',
    avatarUrl: null,
    role: 'Accountant',
    department: 'Finance',
    location: 'Denver HQ',
    status: 'absent',
    scheduledStart: '07:30',
    scheduledEnd: '16:00',
    todayMinutes: 0,
    weekMinutes: 1410,
    exceptions: [{ type: 'missed_punch' }],
    punches: [
      { date: '2026-02-21', minutesLate: 12 },
      { date: '2026-02-28', minutesLate: 8 },
    ],
  },
  {
    id: 'e-112',
    name: 'Emma Wilson',
    avatarUrl: null,
    role: 'Stock Associate',
    department: 'Retail',
    location: 'Boulder',
    status: 'pto',
    scheduledStart: '11:00',
    scheduledEnd: '19:00',
    todayMinutes: 0,
    weekMinutes: 980,
    punches: [
      { date: '2026-02-18', minutesLate: 0 },
      { date: '2026-02-25', minutesLate: 0 },
    ],
  },
];

const alerts: Alert[] = [
  {
    id: 'a-1',
    employeeId: 'e-101',
    message: 'On break 36m (limit 30m)',
    timestamp: '2026-03-02T13:36:00Z',
    severity: 'high',
    type: 'break',
    cta: 'message',
  },
  {
    id: 'a-2',
    employeeId: 'e-102',
    message: 'Missed clock-in',
    timestamp: '2026-03-02T08:16:00Z',
    severity: 'high',
    type: 'missed_clock_in',
    cta: 'fix_punch',
  },
  {
    id: 'a-3',
    employeeId: 'e-103',
    message: 'Approaching overtime',
    timestamp: '2026-03-02T14:15:00Z',
    severity: 'medium',
    type: 'overtime',
    cta: 'acknowledge',
  },
];

const insights: Insight[] = [
  {
    id: 'i-1',
    employeeId: 'e-101',
    summary: 'Jake: 4 late arrivals in 2 weeks',
    trend: 'worsening',
    impactNote: 'Coverage gaps are cascading into first-shift handoff.',
    suggestedActions: ['send_reminder', 'schedule_1_1', 'add_private_note', 'escalate_hr'],
    evidence: [
      { date: '2026-02-19', note: 'Late by 9m' },
      { date: '2026-02-21', note: 'Late by 11m' },
      { date: '2026-02-25', note: 'Late by 7m' },
      { date: '2026-02-28', note: 'Late by 10m' },
    ],
  },
  {
    id: 'i-2',
    employeeId: 'e-104',
    summary: 'Priya: attendance reliability dropped this month',
    trend: 'worsening',
    impactNote: 'Supervisor coverage risk on opening shifts.',
    suggestedActions: ['schedule_1_1', 'add_private_note', 'escalate_hr'],
    evidence: [
      { date: '2026-02-14', note: 'Unplanned absence' },
      { date: '2026-02-22', note: 'Late by 6m' },
      { date: '2026-03-02', note: 'Absent at scheduled start' },
    ],
  },
  {
    id: 'i-3',
    employeeId: 'e-106',
    summary: 'Nora: early departures are stabilizing',
    trend: 'improving',
    impactNote: 'Short-term risk reduced, monitor through next payroll cycle.',
    suggestedActions: ['send_reminder', 'add_private_note'],
    evidence: [
      { date: '2026-02-10', note: 'Left early by 17m' },
      { date: '2026-02-17', note: 'Left early by 12m' },
      { date: '2026-03-02', note: 'Left early by 8m' },
    ],
  },
];

function withDelay<T>(value: T): Promise<T> {
  return new Promise((resolve) => {
    setTimeout(() => resolve(value), 150);
  });
}

export function fetchEmployees(): Promise<Employee[]> {
  return withDelay(employees);
}

export function fetchAlerts(): Promise<Alert[]> {
  return withDelay(alerts);
}

export function fetchInsights(): Promise<Insight[]> {
  return withDelay(insights);
}
